### ISSUE TITLE
Ansible fails on a fresh install

### ISSUE THREAD

**Issue by jdeanwallace** [tiny-pilot/ansible-role-tinypilot#156] opened 2021-11-10 16:24 UTC
When running `quick-install` for the first time on a device running raspbian lite (kernel versions `>= 5.10` and `< 5.15`), I get the following error:

```
RUNNING HANDLER [ansible-role-tinypilot : start usb-gadget service] ******************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to start service usb-gadget: Job for usb-gadget.service failed because the control process exited with error code.\nSee \"systemctl status usb-gadget.service\" and \"journalctl -xe\" for details.\n"}
```

It fails to run the [`start usb-gadget service`](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/master/tasks/install_usb_gadget.yml#L112) handler introduced by https://github.com/tiny-pilot/ansible-role-tinypilot/pull/155

Seeing as we're only [enabling the the OTG gadget at boot](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/master/tasks/install_usb_gadget.yml#L21), the `usb-gadget` cannot be started until the device is rebooted.

Possible solutions:
1. Simply ignore errors on the handler (i.e. start `usb-gadget` on best effort). This allows a fresh-install to continue and allows a update-install to actually start the gadget without a reboot.
2. Remove the handler and always rely on a reboot. This isn't ideal for when you simply want to update the software.

**Comment by mtlynch** [comment] 2021-11-10 16:59
Thanks for catching this!

Can we keep track of whether we need a reboot to enable the OTG gadget and skip the [load HID module](https://github.com/tiny-pilot/ansible-role-tinypilot/pull/155/files#diff-7310cfc9b8b06fc200c0bd72853a08434d85f629dfe8e42188865cdfd3f99bebR108) play if there's a pending reboot? We should be able to track whether either of the [dwc2](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/d7da80c474b8b28d9872b77a8df7654fea76320d/tasks/install_usb_gadget.yml#L17) [plays](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/d7da80c474b8b28d9872b77a8df7654fea76320d/tasks/install_usb_gadget.yml#L29) caused a change and use that information to decide whether we need a reboot.

**Comment by mtlynch** [comment] 2021-11-10 17:07
Closing as a dupe of #151 now that we've reverted the associated PR.

**Closed by mtlynch** 2021-11-10 17:07 UTC
